011-devops-directive-docker-course
docker-compose-debug.yml

docker-compose-debug.yml
version: “3.9
services:
       api-node:
              commands:
                      -“npm”
                      - “run”
                      - “debug-docker”
               ports:
                      - “3000:3000”
                      - “9229:9229”
       api-golang:  
              commands:
                      - “div”
                      - “debug”
                      - “/app/main.go”
                      - “- -listen:4000”
                      - “- -headless=true”
                      - “- -log=true”
                      - “- -log-output=debugger,debuglineerr,gdbwire,lldbout,rpc”
                      - “- -accept-multiclient”
                      - “- -continue”
                      - “api-version=2”
               ports:
                      -  “8080:8080”
                      -  “4000:4000”
